version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: tododb
      GIN_MODE: release
    depends_on:
      - db
    restart: on-failure
    networks:
      - todo-network

  db:
    image: postgres:15
    container_name: todo-db
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - todo-network

volumes:
  pgdata:

networks:
  todo-network:
    driver: bridge